import Script from 'next/script';
import { Fragment } from 'react';

export default function BandsintownWidget() {
  return (
    <Fragment>
      <Script src="https://widgetv3.bandsintown.com/main.min.js" />
      <a
        className="bit-widget-initializer"
        data-artist-name="id_15523621"
        data-background-color="rgba(33,28,28,1)"
        data-separator-color="rgba(241,236,199,1)"
        data-text-color="rgba(241,236,199,1)"
        data-auto-style="true"
        data-button-label-capitalization="uppercase"
        data-header-capitalization=""
        data-location-capitalization="capitalize"
        data-venue-capitalization="capitalize"
        data-display-local-dates="true"
        data-local-dates-position="tab"
        data-display-past-dates="true"
        data-display-details="false"
        data-display-lineup="false"
        data-display-start-time="false"
        data-social-share-icon="true"
        data-display-limit="all"
        data-date-format="MMM. D, YYYY"
        data-date-orientation="horizontal"
        data-date-border-color="#4A4A4A"
        data-date-border-width="1px"
        data-date-capitalization="capitalize"
        data-date-border-radius="10px"
        data-event-ticket-cta-size="medium"
        data-event-custom-ticket-text=""
        data-event-ticket-text="TICKETS"
        data-event-ticket-icon=""
        data-event-ticket-cta-text-color="rgba(241,236,199,1)"
        data-event-ticket-cta-bg-color="rgba(255,255,255,0)"
        data-event-ticket-cta-border-color="rgba(241,236,199,1)"
        data-event-ticket-cta-border-width="1px"
        data-event-ticket-cta-border-radius="0px"
        data-sold-out-button-text-color="rgba(33,28,28,1)"
        data-sold-out-button-background-color="rgba(74,74,74,0)"
        data-sold-out-button-border-color="rgba(33,28,28,1)"
        data-sold-out-button-clickable="true"
        data-event-rsvp-position="left"
        data-event-rsvp-cta-size="medium"
        data-event-rsvp-only-show-icon=""
        data-event-rsvp-text="REMIND ME"
        data-event-rsvp-icon=""
        data-event-rsvp-cta-text-color="rgba(241,236,199,1)"
        data-event-rsvp-cta-bg-color="rgba(255,255,255,0)"
        data-event-rsvp-cta-border-color="rgba(241,236,199,1)"
        data-event-rsvp-cta-border-width="1px"
        data-event-rsvp-cta-border-radius="0px"
        data-follow-section-position="hidden"
        data-follow-section-alignment="center"
        data-follow-section-header-text="Get updates on new shows, new music, and more."
        data-follow-section-cta-size="medium"
        data-follow-section-cta-text="FOLLOW"
        data-follow-section-cta-icon="true"
        data-follow-section-cta-text-color="rgba(241,236,199,1)"
        data-follow-section-cta-bg-color="rgba(255,251,251,0)"
        data-follow-section-cta-border-color="rgba(241,236,199,1)"
        data-follow-section-cta-border-width="1px"
        data-follow-section-cta-border-radius="0px"
        data-play-my-city-position="bottom"
        data-play-my-city-alignment="center"
        data-play-my-city-header-text="Don't see a show near you?"
        data-play-my-city-cta-size="medium"
        data-play-my-city-cta-text="REQUEST A SHOW"
        data-play-my-city-cta-icon="true"
        data-play-my-city-cta-text-color="rgba(241,236,199,1)"
        data-play-my-city-cta-bg-color="rgba(74,74,74,0)"
        data-play-my-city-cta-border-color="rgba(241,236,199,1)"
        data-play-my-city-cta-border-width="1px"
        data-play-my-city-cta-border-radius="0px"
        data-optin-font=""
        data-optin-text-color=""
        data-optin-bg-color=""
        data-optin-cta-text-color=""
        data-optin-cta-bg-color=""
        data-optin-cta-border-width=""
        data-optin-cta-border-radius=""
        data-optin-cta-border-color=""
        data-language="en"
        data-layout-breakpoint="900"
        data-app-id=""
        data-affil-code=""
        data-bit-logo-position="bottomRight"
        data-bit-logo-color="rgba(241,236,199,1)"
      />
    </Fragment>
  );
}
